export const CartActionTypes = {
    'SET_TOOGLE_VISIBILITY': 'SET_TOOGLE_VISIBILITY',
    'ADD_ITEM': 'ADD_ITEM',
    'REMOVE_ITEM': 'REMOE_ITEM',
    'CLEAR_ITEM_FROM_CART': 'CLEAR_ITEM_FROM_CART',
    'CLEAR_CART': 'CLEAR_CART',

    'ADD_ITEM_START': 'ADD_ITEM_START',
    'ADD_ITEM_SUCCESS': 'ADD_ITEM_SUCCESS',
    'ADD_ITEM_FAILURE': 'ADD_ITEM_FAILURE',

    'REMOVE_ITEM_START': 'REMOVE_ITEM_START',
    'REMOVE_ITEM_SUCCESS': 'REMOVE_ITEM_SUCCESS',
    'REMOVE_ITEM_FAILURE': 'REMOVE_ITEM_FAILURE',

    'CLEAR_ITEM_START': 'CLEAR_ITEM_START',
    'CLEAR_ITEM_SUCCESS': 'CLEAR_ITEM_SUCCESS',
    'CLEAR_ITEM_FAILURE': 'CLEAR_ITEM_FAILURE',

    'LOAD_CART_START': 'LOAD_CART_START',
    'LOAD_CART_SUCCESS': 'LOAD_CART_SUCCESS',
    'LOAD_CART_FAILURE': 'LOAD_CART_FAILURE',

    'CART_LOADING': 'CART_LOADING'
}

export default CartActionTypes;