export const CartActionTypes = {
    'SET_TOOGLE_VISIBILITY': 'SET_TOOGLE_VISIBILITY',
    'ADD_ITEM': 'ADD_ITEM',
    'REMOVE_ITEM': 'REMOE_ITEM',
    'CLEAR_ITEM_FROM_CART': 'CLEAR_ITEM_FROM_CART',
    'CLEAR_CART': 'CLEAR_CART'
}